# Generated by Django 5.1.7 on 2025-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_message_options_alter_phonenumber_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='api_verified',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='test_message_sent',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='webhook_configured',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='is_configured',
            field=models.BooleanField(default=False, help_text="Check when you've completed all the configuration steps", verbose_name='Configuration Complete'),
        ),
    ]
