# Generated by Django 5.1.7 on 2025-04-05 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_remove_phonenumber_api_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='access_token',
            field=models.CharField(blank=True, help_text='Token used for API authentication', max_length=255, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10, verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_number',
            field=models.CharField(max_length=50, verbose_name='from number'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='media ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, null=True, verbose_name='media URL'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='message ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('location', 'Location'), ('template', 'Template'), ('button', 'Button'), ('interactive', 'Interactive')], max_length=20, verbose_name='message type'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.phonenumber'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='received', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_number',
            field=models.CharField(max_length=50, verbose_name='to number'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Phone Number ID'),
        ),
    ]
