# Generated by Django 5.1.8 on 2025-04-08 08:32

from django.db import migrations, models

import superapp.apps.whatsapp.models.phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_alter_message_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='verify_token',
            field=models.CharField(blank=True, default=superapp.apps.whatsapp.models.phone_number.generate_uuid, help_text='Token used to verify webhook requests from WhatsApp', max_length=64, verbose_name='Webhook Verify Token'),
        ),
    ]
