# Generated by Django 5.1.8 on 2025-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_phonenumber_verify_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_mime_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='media mime type'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('location', 'Location'), ('template', 'Template'), ('button', 'Button'), ('interactive', 'Interactive')], max_length=20, null=True, verbose_name='media type'),
        ),
    ]
