# Generated by Django 5.1.8 on 2025-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_message_media_mime_type_message_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='metadata'),
        ),
    ]
