# Generated by Django 5.1.8 on 2025-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_message_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media_url',
        ),
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_media/', verbose_name='Media file'),
        ),
    ]
