# Generated by Django 5.1.8 on 2025-04-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_remove_message_media_url_message_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='raw_message',
            field=models.JSONField(blank=True, null=True, verbose_name='raw message'),
        ),
    ]
