# Generated by Django 5.1.8 on 2025-04-08 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='message ID'),
        ),
    ]
