# Generated by Django 5.1.8 on 2025-04-08 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_alter_message_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Template ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('language', models.CharField(choices=[('en', 'English'), ('en_US', 'English (US)'), ('en_GB', 'English (UK)'), ('es', 'Spanish'), ('es_ES', 'Spanish (Spain)'), ('es_LA', 'Spanish (Latin America)'), ('pt_BR', 'Portuguese (Brazil)'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ru', 'Russian'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('zh_CN', 'Chinese (Simplified)'), ('zh_TW', 'Chinese (Traditional)'), ('hi', 'Hindi')], default='en', max_length=10, verbose_name='Language')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('category', models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('MARKETING', 'Marketing'), ('UTILITY', 'Utility')], default='UTILITY', max_length=20, verbose_name='Category')),
                ('header_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Header Text')),
                ('header_type', models.CharField(blank=True, help_text='Type of header: TEXT, IMAGE, DOCUMENT, VIDEO', max_length=20, null=True, verbose_name='Header Type')),
                ('body_text', models.TextField(verbose_name='Body Text')),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer Text')),
                ('components', models.JSONField(blank=True, help_text='JSON representation of template components', null=True, verbose_name='Components')),
                ('buttons', models.JSONField(blank=True, help_text='JSON representation of template buttons', null=True, verbose_name='Buttons')),
                ('examples', models.JSONField(blank=True, help_text='Example values for template variables', null=True, verbose_name='Examples')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='whatsapp.phonenumber', verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['-created_at'],
                'unique_together': {('phone_number', 'name', 'language')},
            },
        ),
    ]
