# Generated by Django 5.1.8 on 2025-04-08 12:58

import superapp.apps.whatsapp.models.phone_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0015_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='webhook_token',
            field=models.CharField(blank=True, default=superapp.apps.whatsapp.models.phone_number.generate_uuid, help_text='Token used to secure the webhook URL', max_length=64, verbose_name='Webhook URL Token'),
        ),
    ]
