# Generated by Django 5.1.8 on 2025-04-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0016_phonenumber_webhook_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.template'),
        ),
        migrations.AddField(
            model_name='message',
            name='template_variables',
            field=models.JSONField(blank=True, help_text='Variables used in the template, including body parameters and button parameters', null=True, verbose_name='template variables'),
        ),
    ]
