# Generated by Django 5.1.8 on 2025-04-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0017_message_template_message_template_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='template_variables',
            field=models.JSONField(default=dict, help_text='Variables used in the template, including body parameters and button parameters', verbose_name='template variables'),
        ),
    ]
