# Generated by Django 5.1.8 on 2025-04-08 14:21

import django.core.validators
import superapp.apps.whatsapp.models.contact
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0018_alter_message_template_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text="International format without '+' (e.g., 40777777777)", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits', regex='^\\d+$'), superapp.apps.whatsapp.models.contact.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='template',
            name='language',
            field=models.CharField(choices=[('ro', 'Romanian'), ('en', 'English'), ('en_US', 'English (US)'), ('en_GB', 'English (UK)'), ('es', 'Spanish'), ('es_ES', 'Spanish (Spain)'), ('es_LA', 'Spanish (Latin America)'), ('pt_BR', 'Portuguese (Brazil)'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ru', 'Russian'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('zh_CN', 'Chinese (Simplified)'), ('zh_TW', 'Chinese (Traditional)'), ('hi', 'Hindi')], default='en', max_length=10, verbose_name='Language'),
        ),
    ]
