# Generated by Django 5.1.8 on 2025-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0020_message_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('location', 'Location'), ('template', 'Template'), ('button', 'Button'), ('interactive', 'Interactive')], max_length=20, null=True, verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='message',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='error code'),
        ),
        migrations.AddField(
            model_name='message',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='error message'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='read at'),
        ),
    ]
