# Generated by Django 5.1.8 on 2025-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0021_message_content_type_message_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='business_id',
            field=models.CharField(blank=True, help_text='Facebook Business ID for template management', max_length=100, null=True, verbose_name='Facebook Business ID'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='waba_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business Account ID for template management', max_length=100, null=True, verbose_name='WhatsApp Business Account ID'),
        ),
    ]
