# Generated by Django 5.1.8 on 2025-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0022_phonenumber_business_id_phonenumber_waba_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='language',
            field=models.CharField(choices=[('ro', 'Romanian'), ('en', 'English'), ('de', 'Deutsch')], default='ro', max_length=10, verbose_name='Language'),
        ),
    ]
