# Generated by Django 5.1.8 on 2025-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0023_alter_template_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='conversation ID'),
        ),
    ]
