# Generated by Django 5.1.8 on 2025-04-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0024_message_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='language',
            field=models.CharField(default='ro', max_length=10, verbose_name='Language'),
        ),
    ]
